#services:
#  static-site:
#    build: .
#    image: nginx:alpine
#    container_name: static-site
#    restart: unless-stopped
#    volumes:
#      - ./html:/usr/share/nginx/html:ro
#    networks:
#      - web
#    healthcheck:
#      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#
#networks:
#  web:
#    external: true

services:
  blog:
    build: .
    container_name: blog
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
